CREATE TABLE IF NOT EXISTS users
(
    user_id       bigint generated by default as identity primary key,
    user_email    varchar(100) NOT NULL UNIQUE,
    user_name     varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS item_requests
(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    requester_id bigint NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT pk_request_id PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id           bigint generated by default as identity NOT NULL,
    item_name         varchar(100) NOT NULL,
    item_description  varchar(200) NOT NULL,
    item_available    boolean,
    item_owner        bigint NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    request_id  BIGINT REFERENCES item_requests (request_id) ON DELETE CASCADE,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id      bigint generated by default as identity primary key,
    comment_text    varchar(800) NOT NULL,
    item_id         bigint NOT NULL REFERENCES items (item_id) ON DELETE CASCADE,
    author_id       bigint NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL
    CHECK(created >= CAST(now() AS DATE))
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id          bigint generated by default as identity primary key,
    booking_start_time  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    booking_end_time    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id             bigint NOT NULL REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id           bigint NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    approved            varchar(20) NOT NULL
    CHECK(booking_start_time >= CAST(now() AS DATE))
    CHECK(booking_end_time >= CAST(now() AS DATE))
);